# Welcome to Jekyll!

title: "puyokura's tech blog"
description: "技術的な知見や備忘録を公開するブログ。"
url: "https://puyokura.github.io"
baseurl: ""
repository: "puyokura/puyokura.github.io"
locale: "ja-JP"

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed

# Author
author:
  name: "puyokura"

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'